CREATE DATABASE IF NOT EXISTS `multimedia_db`;
USE `multimedia_db`;
DROP TABLE files;

CREATE TABLE IF NOT EXISTS files(
	`id` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

